#image: jbakosi/quinoa-docker:debian-testing-clang-alltpl
image: test

script:
  - mkdir -p tpl/build
  - cd tpl/build
  - cmake -D CMAKE_CXX_COMPILER=mpic++ -D CMAKE_C_COMPILER=mpicc -D CMAKE_Fortran_COMPILER=mpif90 -D CMAKE_BUILD_TYPE=Debug -D STDLIBCPP=libstdc++ ..
  - make -sj4
  - cd -
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=mpic++ -D CMAKE_C_COMPILER=mpicc -D CMAKE_BUILD_TYPE=Debug -D STDLIBCPP=libstdc++ ../src
  - make -sj4
  - Main/charmrun +p4 Main/unittest -v
  - ctest -j4
