build:
  image: jbakosi/quinoa-testing:latest
  commands:
    - source /usr/share/modules/init/bash
    - module load mkl gnu/system openmpi/1.10.2/gnu/system
    - cd /home/quinoa/quinoa
    - mkdir tpl/build; cd tpl/build; cmake .. ; make -sj4 ; cd -
    - mkdir build ; cd build ; cmake -G Ninja ../src ; ninja ; cd -
#  - Main/charmrun +p4 Main/unittest -v
#  - ctest -j4
