build:
  image: jbakosi/quinoa-testing:latest
  commands:
    - source /usr/share/modules/init/bash
    - module load $$MKL $$COMPILER openmpi/1.10.2/$$COMPILER ; module list
    - sudo chown -R tester:tester /drone/src
    - mkdir tpl/build; cd tpl/build; cmake -D STDLIBCPP=$$STDLIBCPP -D CMAKE_BUILD_TYPE=$$BUILD .. ; make -sj`/~cpus.sh` ; cd -
#    - mkdir build ; cd build ; cmake -D STDLIBCPP=$$STDLIBCPP -D CMAKE_BUILD_TYPE=$$BUILD -G Ninja ../src ; ninja ; cd -
#    - cd build; ../script/run_tests.sh ; cd -

cache:
  mount:
    - .git

matrix:
  BUILD:
    - Debug
#    - Release
  COMPILER:
#    - gnu/system
    - clang/system
#    - intel/latest
  MKL:
    - mkl
    -           # test absence of MKL
  STDLIBCPP:
    - libc++
    - libstdc++
