build:
  image: jbakosi/quinoa-testing:latest
  commands:
    - source /usr/share/modules/init/bash
    - module load mkl gnu/system openmpi/1.10.2/gnu/system ; module list
    - cd /home/quinoa/quinoa
    - mkdir tpl/build; cd tpl/build; cmake .. ; make -sj$(nproc) ; cd -
    - mkdir build ; cd build ; cmake -G Ninja ../src ; ninja ; cd -
    - cd build ; charmrun +p$(nproc) Main/unittest -v ; cd -
    - cd build ; ctest -j$(nproc) -E Big ; cd -
