language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get install gfortran openmpi-bin libopenmpi-dev libhdf5-serial-dev libnetcdf-dev libexodusii-dev libpstreams-dev libhypre-dev

before_script:
  - mkdir build
  - cd build
  - cmake ../tpl

script: make
