language: cpp

compiler:
  - gcc

before_install:
  - openssl aes-256-cbc -K $encrypted_b754884effbf_key -iv $encrypted_b754884effbf_iv -in config/travisci_rsa.enc -out config/travisci_rsa -d
  - chmod 0600 config/travisci_rsa
  - cp config/travisci_rsa ~/.ssh/id_rsa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:robotics/ppa
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository ppa:git-core/ppa
  - sudo apt-get update
  - sudo apt-get install -y git cmake gcc-4.9 g++-4.9 gfortran openmpi-bin libopenmpi-dev libhdf5-serial-dev libnetcdf-dev libexodusii-dev libpstreams-dev libboost-all-dev liblapack-dev liblapacke-dev lcov doxygen
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
  - mpicc --version
  - mpic++ --version

before_script:
  - mkdir -p tpl/build
  - cd tpl/build
  - cmake -D CMAKE_CXX_COMPILER=mpic++ -D CMAKE_C_COMPILER=mpicc -D CMAKE_Fortran_COMPILER=mpif90 ..
  - make -sj2
  - cd ../..
  - mkdir build
  - cd build
  - cmake -D CMAKE_CXX_COMPILER=mpic++ -D CMAKE_C_COMPILER=mpicc ../src
  - git clone https://github.com/jbakosi/quinoa.git --branch gh-pages --single-branch doc/html
  - cd doc/html
  - git rm -rf .
  - cd -
  - make doc
  - cd doc/html
  - git add .
  - git config user.name "Jozsef Bakosi"
  - git config user.email "jbakosi@lanl.gov"
  - git commit -m "Automated documentation build for changeset $(git rev-parse --verify HEAD)."
  - git push origin gh-pages

script: make -s
