language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install gfortran openmpi-bin openmpi-dev libhdf5-dev libnetcdf-def libexodusii-dev libpstreams-dev libhypre-dev

before_script:
  - mkdir build
  - cd build
  - cmake ../tpl

script: make
