os:
  - osx

compiler:
  - clang

before_install:
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew install open-mpi ninja
  - brew install --build-from-source homebrew/dupes/lapack

script:
  - mkdir tpl/build ; cd tpl/build ; cmake -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx -G Ninja .. ; ninja ; cd -
  - mkdir build ; cd build ; cmake -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx -G Ninja ../src ; ninja ; cd -
#  - cd build; ../script/run_tests.sh ; cd -

