os:
  - osx

compiler:
  - gcc

env:
  global:
    - HOMEBREW_CC=/usr/local/bin/gcc
    - HOMEBREW_CXX=/usr/local/bin/g++

before_install:
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew outdated gcc || brew upgrade gcc
  - brew install open-mpi ninja pugixml
  - brew install homebrew/science/hdf5 --with-mpi
  - brew install homebrew/science/gmsh homebrew/science/hypre

script:
  - mkdir tpl/build ; cd tpl/build ; cmake -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpif90 ..
  - make -sj2
  - cd -
  - mkdir build ; cd build ; cmake -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx -D BUILD_SHARED_LIBS=on -G Ninja ../src
  - ninja
  - cd -
#  - cd build; ../script/run_tests.sh ; cd -

