os:
  - osx

compiler:
  - clang

before_install:
  - brew update
  - brew outdated cmake || brew upgrade cmake
  - brew install open-mpi ninja pugixml homebrew/science/gmsh homebrew/science/hypre

script:
  - mkdir tpl/build ; cd tpl/build ; cmake -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx -DCMAKE_Fortran_COMPILER=mpif90 ..
  - make -sj2
  - cd -
  - mkdir build ; cd build ; cmake -D CMAKE_C_COMPILER=mpicc -D CMAKE_CXX_COMPILER=mpicxx -G Ninja ../src
  - ninja
  - cd -
  - cd build ; ../script/run_tests.sh ; cd -
